config/routes.rb
QuickTally::Application.routes.draw do
  resources :movies, only: [:index, :show] do
    resources :ratings, only: [:create]
  end
  resources :filter_movies, only: [:index, :create]

  root 'home#index'

end

app/models/in_theater_movies.rb
class InTheaterMovies < MovieFetcher
  attr_reader :url

  def initialize
    super
    @url = "http://api.rottentomatoes.com/api/public/v1.0/lists/movies/in_theaters.json"
    @results = []
  end

  def results
    @results.flatten.uniq {|result| result["id"]}
  end

  def fetch
    begin
      1.upto(5) do |page|
        response = connection.get do |req|
          req.params['page_limit'] = 50
          req.params['apikey'] = api_key
          req.params['page'] = page
        end
        result = JSON.parse(response.body)["movies"]
        puts "found #{result.size} movies" if result
        @results << result if result
        sleep 1
      end
    rescue => e
      Rails.logger.error e
      []
    end
  end

end

app/models/movie.rb
class Movie < ActiveRecord::Base
  SEE_AT_THEATER = "See At Theater"
  SEE_AT_HOME    = "Wait For NetFlix"
  DONT_SEE       = "Don't Waste Your Time"

  include PgSearch

  pg_search_scope :search_full_text, :against => {
    :title => 'A',
    :description => 'B'
  }

  scope :in_theaters, -> {where(in_theaters: true).order(critics_score: :desc)}

  def self.mark_all_as_out_of_theater
    all.each {|movie| movie.mark_as_out_of_theater}
  end

  def mark_as_in_theaters
    update_attribute :in_theaters, true
  end

  def mark_as_out_of_theater
    update_attribute :in_theaters, false
  end

  def total_votes
    positive_count + neutral_count + negative_count
  end

  def viewer_consensus
    viewer_results.sort_by {|opinion, count| -count }.flatten.first
  end

  def add_rating(rating)
    case rating
    when SEE_AT_THEATER then update_attribute :positive_count, (positive_count + 1)
    when SEE_AT_HOME then update_attribute :neutral_count, (neutral_count + 1)
    when DONT_SEE then update_attribute :negative_count, (negative_count + 1)
    end
  end

  def insufficient_votes?
    total_votes < vote_threshold
  end

  def votes_until_live
    vote_threshold - total_votes
  end

  private

  def viewer_results
    {SEE_AT_THEATER => positive_count, SEE_AT_HOME => neutral_count, DONT_SEE => negative_count}
  end

  def vote_threshold
    10
  end
end

app/models/movie_fetcher.rb
class MovieFetcher
  attr_reader :api_key

  def initialize
    @api_key = ENV["ROTTEN_TOMATOES_KEY"]
  end

  def connection
    @conn ||= Faraday.new(url)
  end

end

app/models/new_rental_movies.rb
class NewRentalMovies < MovieFetcher
  attr_reader :url

  def initialize
    super
    @url = "http://api.rottentomatoes.com/api/public/v1.0/lists/dvds/current_releases.json"
  end

  def fetch
    begin
      response = connection.get do |req|
        req.params['page_limit'] = 50
        req.params['apikey'] = api_key
      end
      JSON.parse(response.body)["movies"]
    rescue => e
      Rails.logger.error e
      []
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/filter_movies_controller.rb
class FilterMoviesController < ApplicationController
  def index
  end

  def create
    @movies = Movie.search_full_text(params[:query]).limit(20).order(critics_score: :desc)
    render :index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @movies = Movie.search_full_text("Lego")
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.in_theaters
  end

  def show
    @movie = Movie.find(params[:id])
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :require_correct_rating, only: [:create]

  def create
    movie = Movie.find_by_id(params[:movie_id])
    if session[movie.id]
      flash[:error] = "Halt! You've already rated #{movie.title}"
      redirect_to movies_path
    else
      if movie.add_rating(rating)
        session[movie.id] = "rated"
        flash[:success] = "Woot! #{movie.title} rated"
        redirect_to movies_path
      else
        flash[:error] = "Curses! Try again"
        redirect_to movie_path(movie)
      end
    end
  end

  private

  def require_correct_rating
    if rating.blank? || !approved_rating?
      flash[:error] = "A rating must be of the three provided values below"
      redirect_to movie_path(params[:movie_id]) and return
    end
  end

  def rating
    params[:rating].strip
  end

  def approved_rating?
    rating == Movie::SEE_AT_THEATER ||
    rating == Movie::SEE_AT_HOME ||
    rating == Movie::DONT_SEE
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
  def determine_viewer_style(movie)
    case movie.viewer_consensus
    when Movie::SEE_AT_THEATER then "success"
    when Movie::SEE_AT_HOME then "warning"
    when Movie::DONT_SEE then "danger"
    end
  end

  def determine_critic_style(movie)
    score = movie.critics_score
    if score <= 100 && score > 75
      "success"
    elsif score <= 75 && score > 50
      "warning"
    else
      "danger"
    end
  end

  def cache_key_for_movies
    count = Movie.count
    max_updated_at = Movie.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "movies/all-#{count}-#{max_updated_at}"
  end
end

app/views/filter_movies/index.html.erb
<h2 class="page-title">Search For Movies</h2>

<div class="search-form">
  <p>try searching by...</p>
  <ol class="well">
    <li><b>Title:</b> Anchorman</li>
    <li><b>Actor:</b> Will Ferrell</li>
    <li><b>Character Names:</b> Ron Burgundy</li>
    <li><b>Keywords:</b> News</li>
  </ol>

  <%= form_tag filter_movies_path, method: "post" do %>
    <%= text_field_tag :query, "", autofocus: true, class: "form-control" %>
    <%= submit_tag "Search", class: "btn btn-primary btn-block" %>
  <% end %>
</div>

<% if @movies && @movies.empty? %>
  <h4>No Results Found</h4>
<% elsif @movies %>
    <%= render @movies %>
<% end %>

app/views/home/index.html.erb
<% cache(cache_key_for_movies) do %>

  <h2 class="page-title">Movie Reviews Simplified</h2>

  <ul class="well perks">
    <li><i class="fa fa-dot-circle-o"></i>Easily See All In Theater Movies</li>
    <li><i class="fa fa-dot-circle-o"></i>Add Your Review in 2 Clicks</li>
    <li><i class="fa fa-dot-circle-o"></i>No Signup Needed</li>
    <li><i class="fa fa-dot-circle-o"></i>Critic Reviews From Rotten Tomatoes</li>
    <li><i class="fa fa-dot-circle-o"></i>Actionable User Reviews</li>
    <ul class="reviews">
      <li>See In Theaters</li>
      <li>Wait For NetFlix</li>
      <li>Don't Waste Your Time</li>
    </ul>
  </ul>

  <p>sample review...</p>
  <%= render @movies %>

  <%= link_to "Check Out Currently Playing Movies", movies_path, class: "btn btn-primary btn-block" %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reel Reviews</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
  <%= stylesheet_link_tag "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="navbar navbar-inverse">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-inverse-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Reel Reviews", root_path, class: "navbar-brand" %>
    </div>
    <div class="navbar-collapse navbar-inverse-collapse collapse" style="height: auto;">
      <ul class="nav navbar-nav">
        <li class="active" id="nav-theater"><%= link_to "In Theaters", movies_path, class: "navbar-link" %></li>
        <li id="nav-search"><%= link_to "Search", filter_movies_path, class: "navbar-link" %></li>
      </ul>
    </div>
  </div>

  <div class="container">
    <% flash.each do |name, msg| %>
      <% css_class = name == :error ? "danger" : "success" %>
      <div class="alert alert-<%= css_class %>">
        <button type='button' class='close' data-dismiss='alert'><i class="fa fa-times-circle-o"></i></button>
        <%= msg %>
      </div>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/movies/_movie.html.erb
<% cache(movie) do %>
  <div class="movie well" data-id="<%= movie.id %>">
    <div class="total-votes"><%= movie.total_votes %> votes</div>
    <div style="clear:both"></div>
    <div class="movie-img"><%= image_tag movie.thumbnail_img %></div>
    <div class="top-level-info">
      <h3><%= truncate(movie.title, length: 20) %></h3>
      <div class="critics">
        <span class="label label-<%= determine_critic_style(movie) %>">Critics: <%= movie.critics_score %>%</span>
      </div>
      <div class="viewers">
        <% if movie.insufficient_votes? %>
          <span class="label label-default">Viewers: Need <%= movie.votes_until_live %> more votes</span>
        <% else %>
          <span class="label label-<%= determine_viewer_style(movie) %>">Viewers: <%= movie.viewer_consensus %></span>
        <% end %>
      </div>
    </div>
    <div style="clear:both"></div>
  </div>
<% end %>

app/views/movies/index.html.erb
<% cache(cache_key_for_movies) do %>
  <h2 class="page-title">In Theater Movies</h2>
  <%= render @movies %>
<% end %>

app/views/movies/show.html.erb
<div class="movie-details">
  <div class="movie-img"><%= image_tag @movie.profile_img %></div>
  <div class="facts">
    <h3><%= @movie.title %></h3>
    <div class="critics">
      <span class="label label-<%= determine_critic_style(@movie) %>">Critics: <%= @movie.critics_score %>%</span>
    </div>
    <div class="viewers">
      <% if @movie.insufficient_votes? %>
        <span class="label label-default">Viewers: Need <%= @movie.votes_until_live %> more votes</span>
      <% else %>
        <span class="label label-<%= determine_viewer_style(@movie) %>">Viewers: <%= @movie.viewer_consensus %></span>
      <% end %>
    </div>
    <div class="vote-count">
      <%= @movie.total_votes %> user submitted votes
    </div>
    <div class="time-and-rating">
      <span><%= @movie.runtime %> min</span> |
      <span><%= @movie.rating %></span>
    </div>
  </div>
  <div style="clear:both"></div>
</div>

<div class="synopsis">
  <%= @movie.description %>
</div>

<div class="add-rating">
  <h3>Voice Your Opinion</h3>
  <p>other people should...</p>
  <%= link_to "See At Theater", "#", class: "btn btn-default btn-lg btn-block", id: "positive" %>
  <%= link_to "Wait For NetFlix", "#", class: "btn btn-default btn-lg btn-block", id: "neutral" %>
  <%= link_to "Don't Waste Your Time", "#", class: "btn btn-default btn-lg btn-block", id: "negative" %>
</div>

<div class="form-action">
  <%= form_tag movie_ratings_path(@movie), method: "post" do %>
    <%= hidden_field_tag "rating", "", id: "viewer-vote" %>
    <%= submit_tag "Rate!", class: "btn btn-primary btn-lg btn-block disabled", id: "submit-vote" %>
  <% end %>
</div>